language: julia

os:
  - linux
julia:
  - 1.3
  

script:
  - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaComputing/MKL.jl")); Pkg.add("SharedArrays"); Pkg.test("SharedArrays")'
